#!/bin/sh
# Configuration
game_folder="$HOME/Jagex"
client="${game_folder}/launcher/rs2client"

in_fifo="/tmp/RS2LauncherConnection_${$}_i"
out_fifo="/tmp/RS2LauncherConnection_${$}_o"

# Download game config
config=$(curl -s -L 'https://runescape.com/k=5/jav_config.ws?binaryType=4')
 
# Extract latest crc32 hash
latest=$(echo "$config" | sed -n 's/^download_crc_0=//p')

# Generate hash for the local client
current=$(7z h "$client" | grep 'CRC32  for data:' | cut -d' ' -f18)

# Check to see if we have the latest version
if [ "$((0x$current))" != "$latest" ] ; then
	# Download the client to /tmp
        curl -L -o '/tmp/rs2client.lzma' "https://world16.runescape.com/k=5/client?binaryType=4&fileName=rs2client&crc=${latest}"

	# Decompress file, and make it executable
        7z e '/tmp/rs2client.lzma' -o"${game_folder}/launcher" -aoa && chmod +x "$client"
fi

# Generate launch parameters
params="$(echo "$config" | grep 'param' | cut -d= -f2- | sed 's|=|" "|; s|.*|"&"|') launcher $$" 

# Create FIFOs
mkfifo -m 600 "$in_fifo" "$out_fifo"

# Launch the launcher
"$(dirname $0)/launcher" "$game_folder" "$in_fifo" "$out_fifo" &

# Launch the client
echo "$params" | xargs "$client"

# Delete FIFOs
rm "$in_fifo" "$out_fifo"
